name: pub-daily-crawl
on:
  schedule:
    - cron: "30 6 * * *" #eg 6:30 AM UTC today = 23:30 PST yesterday
  #push:
  #  branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run the run.py to get the latest data
        run: |
          python backend.py

      - name: Setup GIT user
        uses: fregante/setup-git-user@v1
      - name: Push done work
        run: |
          git add --all
          git commit -m "Auto update @ $(date '+%Y-%m-%d')"
          git push --force origin main
